### ISSUE TITLE
更新一组数据

### ISSUE THREAD

**Issue by shuaijiangbo** [chengwb53/echarts-tooltip-auto-show#8]
echart图更新一组数据了怎么整啊？在调一次那个方法，有两个定时器了。

**Comment by chengwubin** [comment]
> echart图更新一组数据了怎么整啊？在调一次那个方法，有两个定时器了。

能详细点不，提供段代码吧

**Comment by zdd2018** [comment]
> 两
你好，问题解决了吗

**Comment by chengwubin** [comment]
> > 两
> > 你好，问题解决了吗

如果是说连续两次调用接口返回处理不同的数据，第一次调用工具的时候返回了一个对象，里面有clear方法，二次调用的时候先调用clear方法清除之前的

**Comment by ZhongHongLi** [comment]
你好你这更新数据怎么操作啊

**Comment by chengwubin** [comment]
> 你好你这更新数据怎么操作啊

这个只处理轮播，怎么更新数据还是用echarts的setOption

**Comment by ZhongHongLi** [comment]
能加个联系方式吗，我这个用你那个有问题



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "chengwb"<notifications@github.com&gt;; 
发送时间: 2020年7月30日(星期四) 中午1:40
收件人: "chengwubin/echarts-tooltip-auto-show"<echarts-tooltip-auto-show@noreply.github.com&gt;; 
抄送: "遗忘的小丑"<www.fz948605929@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [chengwubin/echarts-tooltip-auto-show] 更新一组数据 (#8)





  
你好你这更新数据怎么操作啊
  
这个只处理轮播，怎么更新数据还是用echarts的setOption

**Comment by chengwubin** [comment]
> 能加个联系方式吗，我这个用你那个有问题
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "chengwb"<notifications@github.com&gt;; 发送时间: 2020年7月30日(星期四) 中午1:40 收件人: "chengwubin/echarts-tooltip-auto-show"<echarts-tooltip-auto-show@noreply.github.com&gt;; 抄送: "遗忘的小丑"<[www.fz948605929@qq.com&gt](http://www.fz948605929@qq.com&gt);; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [chengwubin/echarts-tooltip-auto-show] 更新一组数据 (#8) 你好你这更新数据怎么操作啊 这个只处理轮播，怎么更新数据还是用echarts的setOption — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

chengwb53@qq.com
